### ISSUE TITLE
Rendered HTML does not include constraints into the "CrossReference" section

### ISSUE THREAD

**Issue by MLuisaDiezPlatas** [OnToology/OnToology#467] opened 2019-07-11 09:20 UTC

**Comment by mariapoveda** [comment] 2019-07-11 09:25
Do you mean constraints defined for classes?

**Comment by MLuisaDiezPlatas** [comment] 2019-07-11 09:30
Yes
In the subclasses of a class,  a definition like this :
dcterms:abstract max 1 xsd:string

**Comment by mariapoveda** [comment] 2019-07-11 09:57
I think they are in the Cross Ref section, attached to each class.

**Comment by MLuisaDiezPlatas** [comment] 2019-07-11 11:43
I'm sorry for the mistake.
Logically, I meant the CrossReference section.
This section does not show the constraints

**Comment by mariapoveda** [comment] 2019-07-11 12:06
Could you tell us in which repository are you having this problem?

**Comment by MLuisaDiezPlatas** [comment] 2019-07-11 12:09
MLuisaDiezPlatas/structuralElements-ontology
MLuisaDiezPlatas/score-ontology
MLuisaDiezPlatas/date-ontology

**Comment by MLuisaDiezPlatas** [comment] 2019-07-11 12:09
Sorry

MLuisaDiezPlatas/core-ontology

**Comment by mariapoveda** [comment] 2019-07-11 12:19
I used widoco 1.4 locally and it worked. See attachment. 

Maybe @dgarijo and @ahmad88me could have a look at what is happening with the latest widoco version in OnToology.

[postdata .zip](https://github.com/OnToology/OnToology/files/3381937/postdata.zip)

**Comment by ahmad88me** [comment] 2019-07-12 11:10
I tried it and the documentation generated with (Widoco via OnToology) has a missing part compared to Maria's generated one. I also ran Widoco locally (1.4.11) with (and without) `-crossRef` flag and both of them doesn't include the `max` part. @mariapoveda (could it be a different widoco version? could it be a different ontology version?). 
This is the command that I ran: `java -jar widoco-1.4.11-jar-with-dependencies.jar -ontFile postdata-core.owl `

**Comment by MLuisaDiezPlatas** [comment] 2019-07-12 11:24
The versions of the ontology that Maria has tried are the same that you have tried.
In Ontoology this problem happens with all ontologies.
In Widoco directly without using Ontoology, the constraints are generated

**Comment by ahmad88me** [comment] 2019-07-13 08:49
@MLuisaDiezPlatas I can't reproduce that on my machine. Can you provide Widoco's version, the options you used with widoco, and whether it is a fresh documentation or an updated one. 
Thanks,

**Comment by MLuisaDiezPlatas** [comment] 2019-07-16 08:53
I think that the templates in extraction.xsl, that shows bellow, is not executed. I have proved my ontology with LODE and the constraints are shown. @ahmad88me @dgarijo @mariapoveda @ocorcho 

 <xsl:template match="/rdf:RDF/owl:Restriction[exists(rdfs:subClassOf)]">
        <div id="{generate-id()}" class="entity">
            <h3><xsl:value-of select="f:getDescriptionLabel('subclassdefinition')" /><xsl:text> </xsl:text><xsl:call-template name="get.backlink" /></h3>
            <p>
                <xsl:call-template name="exec.owlRestriction" />
                <strong><xsl:text> </xsl:text><xsl:value-of select="f:getDescriptionLabel('issubclassof')" /></strong>
            </p>
            <p style="text-align:right">
                <xsl:apply-templates select="rdfs:subClassOf">
                    <xsl:with-param name="list" select="false()" tunnel="yes" />
                </xsl:apply-templates>
            </p>
        </div>
    </xsl:template>
    
    <xsl:template match="/rdf:RDF/owl:Restriction[exists(owl:equivalentClass)]">
        <div id="{generate-id()}" class="entity">
            <h3><xsl:value-of select="f:getDescriptionLabel('equivalentdefinition')" /><xsl:text> </xsl:text><xsl:call-template name="get.backlink" /></h3>
            <p>
                <xsl:call-template name="exec.owlRestriction" />
                <strong><xsl:text> </xsl:text><xsl:value-of select="f:getDescriptionLabel('isequivalentto')" /></strong>
            </p>
            <p style="text-align:right">
                <xsl:apply-templates select="owl:equivalentClass">
                    <xsl:with-param name="list" select="false()" tunnel="yes" />
                </xsl:apply-templates>
            </p>
        </div>
    </xsl:template>
    
    <xsl:template name="exec.owlRestriction">
        <xsl:apply-templates select="owl:onProperty" />
        <xsl:apply-templates select="element()[not(self::owl:onProperty|self::owl:onClass|self::rdfs:subClassOf|self::owl:equivalentClass)]" />
        <xsl:apply-templates select="owl:onClass" />
    </xsl:template>

**Comment by ahmad88me** [comment] 2019-07-19 10:49
Hi  @MLuisaDiezPlatas 
From my understanding, you were able see these constraints on the generate html using Widoco locally. I tried to same on my machine and I could not see it (see: https://github.com/OnToology/OnToology/issues/467#issuecomment-510847842). 
It would be helpful if you can provide the Widoco version, the ontology version (whether it is latest version in the repo). So I can check whether it is related to Widoco or OnToology. 
Thanks,

**Comment by dgarijo** [comment] 2021-06-01 10:43
Since we got no additional answer, we are closing this issue. If there are further problems, please report it in https://github.com/dgarijo/Widoco/

**Closed by dgarijo** 2021-06-01 10:43 UTC
