### ISSUE TITLE
Anchor links do not work

### ISSUE THREAD

**Issue by ednaru** [OnToology/OnToology#461] opened 2019-05-14 08:54 UTC
I need to create anchor links within a page when explaining some concepts in the ontology (the ontology has not been published yet), these do not work.

**Comment by mariapoveda** [comment] 2019-05-14 09:35
Could you ellaborate a bit more? which page? generated with Widoco?

**Comment by ednaru** [comment] 2019-05-16 13:46
In previous versions of my documentation I had "El concepto principal de este vocabulario es el de [esagm:Evento](#Evento)" and it worked, in latter versions it stopped working. I changed it to: 
El concepto principal de este vocabulario es el de [esagm:Evento](index-es.html#http://vocab.ciudadesabiertas.es/def/sector-publico/agenda-municipal#Evento) and now it works.

**Comment by ahmad88me** [comment] 2019-05-17 08:12
@ednaru I noticed a bug in the content negotiation, I solved it partially a few days ago, but I am not sure if it is the cause.
From my understanding it is solved, so I will close it. Feel free to reopen if the same issue occur again. 
Thanks for reporting.

**Closed by ahmad88me** 2019-05-17 08:12 UTC
